name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  - name: Codeql.Enabled
    value: true
schedules:
  - cron: 0 3 * * *
    branches:
      include:
        - main
resources:
  repositories:
    - repository: self
      type: git
      ref: refs/heads/main
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
trigger: none
pr: none
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    pool:
      name: MSEngSS-MicroBuild2022-1ES
    stages:
      - stage: Build
        jobs:
          - job: Job_1
            displayName: VSCode-Lombok-Nightly
            templateContext:
              mb:
                signing:
                  enabled: true
                  signType: real
                  zipSources: false
                  feedSource: 'https://mseng.pkgs.visualstudio.com/DefaultCollection/_packaging/MicroBuildToolset/nuget/v3/index.json'
              outputs:
                - output: pipelineArtifact
                  artifactName: drop
                  targetPath: $(Build.ArtifactStagingDirectory)
                  displayName: "Publish Artifact: drop"
            steps:
              - checkout: self
                fetchTags: true
              - task: UseNode@1
                displayName: Use Node 20.x
                inputs:
                  version: '20.x'
              # The image does not have jdk preinstalled, we need to download it first.
              - task: PowerShell@2
                displayName: Download JDK 17
                inputs:
                  targetType: 'inline'
                  script: |-
                    New-Item -ItemType Directory -Path "$env:AGENT_TEMPDIRECTORY\downloadjdk"
                    Invoke-WebRequest -Uri "https://aka.ms/download-jdk/microsoft-jdk-17-windows-x64.zip" -OutFile "$env:AGENT_TEMPDIRECTORY\downloadjdk\microsoft-jdk-17-windows-x64.zip"
              - task: JavaToolInstaller@0
                displayName: 'Use Java 17'
                inputs:
                  versionSpec: 17
                  jdkArchitectureOption: x64
                  jdkSourceOption: LocalDirectory
                  jdkFile: $(Agent.TempDirectory)/downloadjdk/microsoft-jdk-17-windows-x64.zip
                  jdkDestinationDirectory: $(Agent.ToolsDirectory)/ms-jdk17
              - script: java --version
                displayName: 'Check Java installation'
              - task: Npm@1
                displayName: 'npm install'
                inputs:
                  verbose: false
              - task: Npm@1
                displayName: 'npm run build-server'
                inputs:
                  command: custom
                  verbose: false
                  customCommand: 'run build-server'
              - task: PowerShell@2
                displayName: Sign Jars
                inputs:
                  targetType: 'inline'
                  script: |-
                    $files = Get-ChildItem -Path . -Recurse -Filter "com.microsoft.java.lombok-*.jar"
                    foreach ($file in $files) {
                        $fileName = $file.Name
                        & dotnet "$env:MBSIGN_APPFOLDER\DDSignFiles.dll" /file:"$fileName" /certs:100010171
                    }
                  workingDirectory: 'plugins'
              - script: npx json@latest -I -f package.json -e "this.aiKey=\"%AI_KEY%\""
                displayName: Replace AI Key
              - task: CmdLine@2
                displayName: Set pre-release versions
                inputs:
                  script: node ./scripts/build/prepare-nightly-build.js
              - script: 'npx vsce@latest package --pre-release -o extension.vsix'
                displayName: 'package vsix'
              ### Copy files for APIScan
              - task: CopyFiles@2
                displayName: "Copy Files for APIScan"
                inputs:
                  Contents: "*.vsix"
                  TargetFolder: $(Agent.TempDirectory)/APIScanFiles
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
              ### Run latest version of APIScan listed at https://www.1eswiki.com/wiki/APIScan_Build_Task
              - task: APIScan@2
                displayName: Run APIScan
                inputs:
                  softwareFolder: $(Agent.TempDirectory)/APIScanFiles
                  softwareName: "vscode-lombok"
                  softwareVersionNum: "$(Build.BuildId)"
                  isLargeApp: false
                  toolVersion: "Latest"
                condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
                env:
                  AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)
              - script: npx @vscode/vsce@latest generate-manifest -i extension.vsix -o extension.manifest
                displayName: 'Generate extension manifest'
              - script: copy extension.manifest extension.signature.p7s
                displayName: 'Prepare manifest for signing'
              - task: CmdLine@2
                displayName: Sign extension
                inputs:
                  script: dotnet %MBSIGN_APPFOLDER%/ddsignfiles.dll /file:extension.signature.p7s /certs:4014052
              - task: CopyFiles@2
                displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
                inputs:
                  Contents: |
                    extension.vsix
                    extension.manifest
                    extension.signature.p7s
                  TargetFolder: '$(Build.ArtifactStagingDirectory)'
