name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Node.js modules
      run: npm install

    - name: Install VSCE
      run: npm install -g vsce

    - name: TSC Compile
      run: npm run compile

    - name: Build VSIX file
      run: vsce package

    - name: Test extension
      run: npm test
